services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transactions
    command: ["postgres", "-c", "max_connections=500"]
  pgbouncer:
    image: edoburu/pgbouncer:latest
    ports:
      - "6432:6432"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/transactions
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      - db
